name:                cassandraaccess
version:             0.1.0.0
github:              "micwypych/haksell-cassandra-access"
license:             BSD3
author:              "Michał Wypych"
maintainer:          "mwypych@agh.edu.pl"
copyright:           "2018 Michał Wypych"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/micwypych/haksell-cassandra-access#readme>

dependencies:
- base >= 4.7 && < 5
- cql >= 4.0
- cql-io
- text
- tinylog
- uuid
- either
- random

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  cassandraaccess-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cassandraaccess

tests:
  cassandraaccess-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cassandraaccess
